### PR TITLE
feat: refresh token

### PR DESCRIPTION
**Pull request by ronderksen**
I'm working on a project where the oauth server returns a refresh_token and expires_in time. With this PR, a timeout is set when the original token is set. I still have to test it to make sure this works as expected, but I wanted to open a draft PR for early feedback :).

### CODE REVIEW

**Comment by gardner** [comment]
This looks great. How does it test?

**Comment by ronderksen** [comment]
I had to make some changes to the original setup, but it now refreshes the token automatically, if the AuthService is initiated with `autoRefresh: true`. There's also an option to give an amount of slack to the timeout, so that if the OAuth server returns an expires_in of X, then the timeout is triggered at X-refreshSlack (to make sure you get a token before the previous token expires).

**Comment by ronderksen** [comment]
I can add some tests sometime later this week, if you want.

**Comment by ronderksen** [comment]
Thanks for merging! Can you create a new npm version?

**Comment by gardner** [comment]
New npm version posted: 1.0.5

**Pull request merged**
